import streamlit as st
import pandas as pd
import joblib
from datetime import datetime

st.set_page_config(
    page_title="East Region HDB Price Estimator",
    page_icon="🏠",
    layout="wide"
)
    
# Custom styling
st.markdown("""
    <style>
    .main-title {
        font-size: 2.2rem;
        font-weight: 700;
        color: #1a3c5e;
        margin-bottom: 0;
    }
    .subtitle {
        color: #5a6b7d;
        font-size: 1.05rem;
        margin-top: 0.2rem;
    }
    .price-box {
        background-color: #f0f7f4;
        border-left: 6px solid #2e8b57;
        padding: 1.5rem;
        border-radius: 8px;
        margin-top: 1rem;
    }
    </style>
""", unsafe_allow_html=True)

@st.cache_resource
def load_model():
    model = joblib.load("hdb_resale_model.pkl")
    columns = joblib.load("model_columns.pkl")
    return model, columns

model, model_columns = load_model()

st.markdown('<p class="main-title">East Region HDB Resale Price Estimator</p>', unsafe_allow_html=True)
st.markdown('<p class="subtitle">Instant, data-driven price estimates for flats in Bedok, Pasir Ris, and Tampines</p>', unsafe_allow_html=True)
st.divider()

# Category options, exactly matching the training data
TOWN_OPTIONS = ["BEDOK", "PASIR RIS", "TAMPINES"]
FLAT_TYPE_OPTIONS = ["2 ROOM", "3 ROOM", "4 ROOM", "5 ROOM", "EXECUTIVE", "MULTI-GENERATION"]
FLAT_MODEL_OPTIONS = [
    "2-room", "3Gen", "Adjoined flat", "Apartment", "DBSS", "Improved",
    "Maisonette", "Model A", "Model A-Maisonette", "Multi Generation",
    "New Generation", "Premium Apartment", "Premium Maisonette",
    "Simplified", "Standard"
]

col_left, col_right = st.columns([1, 1], gap="large")

with col_left:
    st.subheader("Flat Details")

    town = st.selectbox("Town", TOWN_OPTIONS)
    flat_type = st.selectbox("Flat Type", FLAT_TYPE_OPTIONS)
    flat_model = st.selectbox("Flat Model", FLAT_MODEL_OPTIONS)

    floor_area_sqm = st.slider("Floor Area (sqm)", min_value=38, max_value=200, value=95)

    storey_mid = st.slider("Storey Level", min_value=1, max_value=50, value=8)

    lease_commence_year = st.number_input(
        "Lease Commencement Year",
        min_value=1972, max_value=2022, value=1995, step=1
    )

    predict_clicked = st.button("Get Price Estimate", type="primary", use_container_width=True)

with col_right:
    st.subheader("Estimated Resale Price")

    if predict_clicked:
        # Input validation, defensive check even though sliders already constrain ranges
        today = datetime.now()
        txn_year = today.year
        txn_month = today.month

        if lease_commence_year > txn_year:
            st.error("Lease commencement year cannot be in the future. Please check your input.")
        else:
            try:
                remaining_lease_years = 99 - (txn_year - lease_commence_year)

                # Build input row of zeros matching the model's expected columns
                input_row = pd.DataFrame(0, index=[0], columns=model_columns)

                input_row["floor_area_sqm"] = floor_area_sqm
                input_row["remaining_lease_years"] = remaining_lease_years
                input_row["storey_mid"] = storey_mid
                input_row["txn_year"] = txn_year
                input_row["txn_month"] = txn_month

                town_col = f"town_{town}"
                if town_col in input_row.columns:
                    input_row[town_col] = 1

                flat_type_col = f"flat_type_{flat_type}"
                if flat_type_col in input_row.columns:
                    input_row[flat_type_col] = 1

                flat_model_col = f"flat_model_{flat_model}"
                if flat_model_col in input_row.columns:
                    input_row[flat_model_col] = 1

                prediction = model.predict(input_row)[0]

                st.session_state["prediction"] = prediction
                st.session_state["remaining_lease"] = remaining_lease_years

            except Exception as e:
                st.error(f"Something went wrong generating the estimate: {e}")

    if "prediction" in st.session_state:
        st.markdown(f"""
            <div class="price-box">
                <p style="margin:0; color:#5a6b7d;">Estimated Resale Price</p>
                <p style="margin:0; font-size:2.2rem; font-weight:700; color:#1a3c5e;">
                    ${st.session_state['prediction']:,.0f}
                </p>
                <p style="margin:0.3rem 0 0 0; color:#5a6b7d; font-size:0.9rem;">
                    Remaining lease: {st.session_state['remaining_lease']:.0f} years
                </p>
            </div>
        """, unsafe_allow_html=True)
    else:
        st.info("Fill in the flat details and click **Get Price Estimate** to see a prediction.")

st.divider()
st.caption("Estimates are generated by a Random Forest model trained on HDB resale transactions from 2017 onwards, restricted to Bedok, Pasir Ris, and Tampines. For guidance only, not a substitute for professional valuation.")